site_name: "QuickText"
theme:
  name: "readthedocs"
  palette:
    primary: "dark-blue"
    accent: "dark-blue"
    # scheme: slate Use this for dark mode
    scheme: slate
    # scheme: default Use this for light mode

docs_dir: templates
repo_url: https://github.com/picturate/qtc
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md

